### ISSUE TITLE
Pagination on Griddle doesn't match style guide examples

### ISSUE THREAD

**Issue by coryhouse** [cox-auto-kc/fusion-starter#80]
Note the pagination here: https://coxautokc.github.io/fusion-starterkit/#/atoms

Doesn't match the Griddle pagination here: https://coxautokc.github.io/fusion-starterkit/#/datatables

**Comment by jasonhale** [comment]
@NathanTrost is better suited to answer that.  I believe it's because that is the pagination that comes stock with Griddle.

**Comment by coryhouse** [comment]
@NathanTrost - I assume you opened a TFS ticket to track this? Can you point me at it or reply here?

**Comment by NathanTrost** [comment]
@coryhouse - PBI #53037.  I had originally not made a ticket as I wasn't sure how much work would go in to it.  Made it this morning

**Comment by coryhouse** [comment]
Looks great. Thanks!
